name: checkandchat
description: Check and Chat.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  provider: ^4.0.4
  flutter_rating_bar: ^3.0.1+1
  toast: ^0.1.5
  google_maps_flutter: any
  geolocator: ^5.2.1
  geocoding: ^1.0.5
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  carousel_slider: ^2.1.0
  image_picker: ^0.6.5
  url_launcher: ^5.4.2
  share: ^0.6.3+6
  photo_view: ^0.9.2
  firebase_auth: ^0.16.1
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  firebase_storage: ^3.1.5
  animated_text_kit: 2.4.1
  shared_preferences: 0.5.7
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.5
  flutter_google_places: ^0.1.4+1
  get_it: ^4.0.2
  flutter_country_picker: ^0.1.6
  flutter_time_picker_spinner: ^1.0.6

  fluttertoast: ^4.0.0
  cached_network_image: 2.0.0-rc.1




dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^2.3.2
  easy_localization_loader: ^0.0.2


flutter_icons:
  image_path: "images/appIcon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets :
   - resources/langs/
   - images/NavBar/activity.png
   - images/NavBar/bookmark-filled.png
   - images/NavBar/bookmark.png
   - images/NavBar/me.png
   - images/NavBar/nearby.png
   - images/NavBar/nearbyfilled.png
   - images/searchScreenIcons/filter.png
   - images/searchScreenIcons/sushi.png
   - images/searchScreenIcons/noodles.png
   - images/searchScreenIcons/chilli.png
   - images/searchScreenIcons/thailand.png
   - images/searchScreenIcons/sandwich.png
   - images/searchScreenIcons/crab.png
   - images/searchScreenIcons/ketchup.png
   - images/searchScreenIcons/map.png
   - images/searchScreenIcons/burger.png
   - images/searchScreenIcons/pizza.png
   - images/searchScreenIcons/star-rating.png
   - images/searchScreenIcons/breakfast.png
   - images/nearByIcons/calendar.png
   - images/nearByIcons/hair-dryer.png
   - images/nearByIcons/meal.png
   - images/nearByIcons/more.png
   - images/meScreenIcons/addShopp.png
   - images/meScreenIcons/myShopp.png
   - images/nearByIcons/take-out.png
   - images/nearByIcons/tea.png
   - images/nearByIcons/gas.png
   - images/nearByIcons/shopping.png
   - images/nearByIcons/pharmacy.png
   - images/nearByIcons/accounting.png
   - images/nearByIcons/hospital.png
   - images/nearByIcons/weather.png
   - images/meScreenIcons/about.png
   - images/meScreenIcons/addPhoto.png
   - images/meScreenIcons/addReview.png
   - images/meScreenIcons/findFriends.png
   - images/meScreenIcons/bell.png
   - images/meScreenIcons/heart.png
   - images/meScreenIcons/call.png
   - images/meScreenIcons/chat.png
   - images/meScreenIcons/talk.png
   - images/meScreenIcons/checkin.png
   - images/meScreenIcons/comment.png
   - images/meScreenIcons/cool-filled.png
   - images/meScreenIcons/cool.png
   - images/meScreenIcons/deals-filled.png
   - images/meScreenIcons/deals.png
   - images/meScreenIcons/find.png
   - images/meScreenIcons/friends.png
   - images/meScreenIcons/groubChat.png
   - images/meScreenIcons/happy-filled.png
   - images/meScreenIcons/happy.png
   - images/meScreenIcons/instractions.png
   - images/meScreenIcons/like.png
   - images/meScreenIcons/photo.png
   - images/meScreenIcons/me.png
   - images/meScreenIcons/medal.png
   - images/meScreenIcons/messages.png
   - images/meScreenIcons/more.png
   - images/meScreenIcons/phone.png
   - images/meScreenIcons/prize.png
   - images/meScreenIcons/reservations.png
   - images/meScreenIcons/secretChat.png
   - images/meScreenIcons/share.png
   - images/meScreenIcons/useful-filled.png
   - images/meScreenIcons/useful.png
   - images/meScreenIcons/website.png
   - images/meScreenIcons/app.png
   - images/meScreenIcons/friendRequest.png
   - images/meScreenIcons/userPlaceholder.png
   - images/meal.jpg
   - images/addFriend.png
   - images/meal2.jpg
   - images/meals.jpg
   - images/ahmed.jpg
   - images/Bl.jpg
   - images/marker.png
   - images/BradPitt.jpg
   - images/appIcon.png
   - images/facebook.png
   - images/google.png
   - images/user.png
   - images/placeholder.png
   - images/img_not_available.jpeg
   - images/mimi1.gif
   - images/mimi2.gif
   - images/mimi3.gif
   - images/mimi4.gif
   - images/mimi5.gif
   - images/mimi6.gif
   - images/mimi7.gif
   - images/mimi8.gif
   - images/mimi9.gif

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
  - family: Cairo
    fonts:
    - asset: fonts/Cairo/Cairo-Black.ttf
    - asset: fonts/Cairo/Cairo-Bold.ttf
    - asset: fonts/Cairo/Cairo-ExtraLight.ttf
    - asset: fonts/Cairo/Cairo-Light.ttf
    - asset: fonts/Cairo/Cairo-Regular.ttf
    - asset: fonts/Cairo/Cairo-SemiBold.ttf
      weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages